import { Incident } from '../models/incident.model';

/*
 * Static fixtures live outside services intentionally.
 *
 * Keeps transport concerns separate from test data.
 */

export const INCIDENTS: Incident[] = [
  {
    id: 'INC-101',
    title: 'Payment gateway timeout',
    description: 'Checkout requests are showing elevated latency.',
    status: 'OPEN',
    severity: 'HIGH',
    service: 'Payments',
    createdAt: '2026-05-23T08:30:00Z',
  },
  {
    id: 'INC-102',
    title: 'Authentication failures',
    description: 'Users intermittently unable to log in.',
    status: 'INVESTIGATING',
    severity: 'CRITICAL',
    service: 'Authentication',
    createdAt: '2026-05-22T14:00:00Z',
  },
  {
    id: 'INC-103',
    title: 'Notification delivery delay',
    description: 'Email processing slower than expected.',
    status: 'RESOLVED',
    severity: 'MEDIUM',
    service: 'Notifications',
    createdAt: '2026-05-21T10:00:00Z',
  },
  {
    id: 'INC-104',
    title: 'Reporting API degradation',
    description: 'Analytics endpoints responding slowly.',
    status: 'OPEN',
    severity: 'LOW',
    service: 'Analytics',
    createdAt: '2026-05-20T09:00:00Z',
  },
  {
    id: 'INC-105',
    title: 'Payment gateway retry burst',
    description: 'Failed payments are retrying excessively under peak load.',
    status: 'INVESTIGATING',
    severity: 'HIGH',
    service: 'Payments',
    createdAt: '2026-05-23T11:05:00Z',
  },
  {
    id: 'INC-106',
    title: 'Authentication session drift',
    description: 'User sessions are being invalidated sooner than expected.',
    status: 'OPEN',
    severity: 'MEDIUM',
    service: 'Authentication',
    createdAt: '2026-05-23T09:20:00Z',
  },
  {
    id: 'INC-107',
    title: 'Notification bounce rate spike',
    description: 'Inbound notification delivery failures have increased sharply.',
    status: 'INVESTIGATING',
    severity: 'MEDIUM',
    service: 'Notifications',
    createdAt: '2026-05-22T19:10:00Z',
  },
  {
    id: 'INC-108',
    title: 'Analytics chart rendering issue',
    description: 'Several dashboard charts are missing data points after refresh.',
    status: 'OPEN',
    severity: 'LOW',
    service: 'Analytics',
    createdAt: '2026-05-22T17:45:00Z',
  },
  {
    id: 'INC-109',
    title: 'Payment settlement delay',
    description: 'Settlement batches are delayed beyond expected cutover times.',
    status: 'RESOLVED',
    severity: 'MEDIUM',
    service: 'Payments',
    createdAt: '2026-05-22T15:30:00Z',
  },
  {
    id: 'INC-110',
    title: 'Authentication OTP slowdown',
    description: 'One-time password delivery is slower for some regions.',
    status: 'INVESTIGATING',
    severity: 'CRITICAL',
    service: 'Authentication',
    createdAt: '2026-05-23T08:00:00Z',
  },
  {
    id: 'INC-111',
    title: 'Notification routing failure',
    description: 'Message routing is failing for the mobile notifications channel.',
    status: 'OPEN',
    severity: 'HIGH',
    service: 'Notifications',
    createdAt: '2026-05-23T07:30:00Z',
  },
  {
    id: 'INC-112',
    title: 'Analytics event mismatch',
    description: 'Event counts do not match across the reporting and storage systems.',
    status: 'RESOLVED',
    severity: 'HIGH',
    service: 'Analytics',
    createdAt: '2026-05-21T13:15:00Z',
  },
];